name: Release

on:
   workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-tweak-and-release:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Prepare Go
        uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1.5

      - name: Clone YouTubeHeader
        run: |
          git clone https://github.com/PoomSmart/YouTubeHeader $THEOS/include/YouTubeHeader

      - name: Prepare GNU Make
        run: |
          brew install make
          gmake --version

      - name: Extract Values
        run: |
          NAME=$(grep '^Name:' control | cut -d ' ' -f 2)
          echo "NAME=$NAME" >> $GITHUB_ENV
          PACKAGE=$(grep '^Package:' control | cut -d ' ' -f 2)
          VERSION=$(grep '^Version:' control | cut -d ' ' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          ROOTLESS_DEB_FILE_NAME="${PACKAGE}_${VERSION}_iphoneos-arm64.deb"
          echo "ROOTLESS_DEB_FILE_NAME=$ROOTLESS_DEB_FILE_NAME" >> $GITHUB_ENV

      - name: Generate changelog
        run: go run scripts/generate_changelog.go --version "${{ env.VERSION }}"

      - name: Build packages
        run: gmake package FINALPACKAGE=1

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.VERSION }}
          name: ${{ env.VERSION }}
          files: |
            packages/${{ env.ROOTLESS_DEB_FILE_NAME }}
          body_path: .github/release-notes.md
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ env.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
